---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: mutation test

permissions:
  contents: read

jobs:
  mutation:
    uses: yii2-framework/actions/.github/workflows/infection.yml@670b6444a11798dc2b38f2563dbbcef063dfc0ab # v2.0.1
    with:
      command-options: --threads=4 --ignore-msi-with-no-mutations
      phpstan: true
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
